info.welcome:
  - MeynConsole (1.0)
info.support:
  - MeynConsole (1.0)
  - Developer - Meynrun
  - Contacts
  - Meynrun's discord - meynrun
  - TIMRGER's discord - timrger.offical

command.notfound: Command not found
command.successfully: Successfully