info.welcome:
  - MeynConsole (1.0)
info.support:
  - MeynConsole (1.0)
  - Разработчик - Meynrun
  - Контакты
  - Дискорд Meynrun'а - meynrun
  - Дискорд TIMRGER'а - timrger.offical

command.notfound: Команда не найдена
command.successfully: Успешно